
project_id = "lkenxwnqoazfdoabrpxl"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000", 
  "https://preview--platform-nexus-assets-hub.lovable.app",
  "https://plan.adgeist.ai"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[functions]
serve_port = 54328
function_timeout_seconds = 60

[functions.generate-embeddings]
verify_jwt = false

[functions.regenerate-embeddings]
verify_jwt = false

[functions.create-embedding-search]
verify_jwt = false

[functions.generate-media-plan]
verify_jwt = false
