
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkenxwnqoazfdoabrpxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZW54d25xb2F6ZmRvYWJycHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTE2OTUsImV4cCI6MjA1OTA4NzY5NX0.bHtOSGHRh5Z_wH-EHCIpCCG1TYhN3pE7g73EQBpNSr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize and check storage buckets once at startup to avoid runtime errors
const initializeStorage = async () => {
  try {
    // Check if the platform-logos bucket exists, create if not
    const { data: platformLogosData, error: platformLogosError } = await supabase.storage.getBucket('platform-logos');
    
    if (platformLogosError && platformLogosError.message.includes('does not exist')) {
      console.log('Creating platform-logos bucket...');
      const { error } = await supabase.storage.createBucket('platform-logos', {
        public: true,
        fileSizeLimit: 5 * 1024 * 1024, // 5MB
        allowedMimeTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/svg+xml']
      });
      
      if (error) {
        console.error('Error creating platform-logos bucket:', error);
      } else {
        console.log('Successfully created platform-logos bucket');
      }
    }

    // Check if the assets bucket exists
    const { data: assetsData, error: assetsError } = await supabase.storage.getBucket('assets');
    if (assetsError && assetsError.message.includes('does not exist')) {
      console.log('Assets bucket not found. Please create it in the Supabase dashboard.');
    }
  } catch (error) {
    console.error('Storage initialization error:', error);
  }
};

// Call the initialization function
initializeStorage();
