
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkenxwnqoazfdoabrpxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZW54d25xb2F6ZmRvYWJycHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTE2OTUsImV4cCI6MjA1OTA4NzY5NX0.bHtOSGHRh5Z_wH-EHCIpCCG1TYhN3pE7g73EQBpNSr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize and check storage buckets once at startup to avoid runtime errors
// This function is isolated and doesn't attempt to modify any config files
const initializeStorage = async () => {
  try {
    // Check if the assets bucket exists, but don't try to create it here
    // This is just for diagnostics
    const { data } = await supabase.storage.getBucket('assets');
    if (!data) {
      console.log('Assets bucket not found. Please create it in the Supabase dashboard.');
    }
  } catch (error) {
    console.error('Storage initialization error:', error);
  }
};

// Call the initialization function
initializeStorage();
